version: '{build}'
skip_tags: true
image: Visual Studio 2019
branches:
  only:
    - master
    - deploy
environment:
  # this is how to set encrypted variable. Go to "Settings" -> "Encrypt YAML" page in account menu to encrypt data.
  nuget_api_key:
    secure: bQrrcrk3oT7hObubXjbx6Qkw76tsKeDzC6r7cLhc9pEzy8T75uQDQIJhu800BDaw

build_script:
  - dotnet --info
  - dotnet restore
  - dotnet build
  # see https://github.com/Mongo2Go/Mongo2Go/issues/65
  # - dotnet test src/Mongo2GoTests --diag
  # - echo *** Test finished ***

